let testPostIt = new PostIt (50, 50, 200, 300, "red", "Ecrivez Ici", 1 )
testPostIt.affichePostIt()
testPostIt.deplacement(100, 200)
testPostIt.affichePostIt()
testPostIt.redimensionnement(100, 100)
testPostIt.affichePostIt()
testPostIt.changementText("Salut")
testPostIt.affichePostIt()
testPostIt.changerCouleur("blue")
testPostIt.affichePostIt()